# Standards: 1.2
---
- name: Install required packages
  loop:
    - unzip
  package:
    name: "{{ item }}"
    state: present
  tags:
    - packwiz

- name: Check existing install
  register: packwiz_check
  check_mode: False
  stat:
    path: /usr/bin/packwiz
  tags:
    - packwiz

- name: Download release binary
  when: not packwiz_check.stat.exists or packwiz_force
  unarchive:
    src: "{{ packwiz_download }}"
    dest: /usr/bin
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    remote_src: yes
  tags:
    - packwiz

...
